In [5]:
import pandas as pd 
import numpy as np
import nltk

In [7]:
nltk.download('gutenberg')

[nltk_data] Downloading package gutenberg to C:\Users\BÜLLÜK
[nltk_data]     TOKATLAYAN\AppData\Roaming\nltk_data...
[nltk_data]   Unzipping corpora\gutenberg.zip.


True

In [9]:
from nltk.corpus import gutenberg

In [14]:
data=gutenberg.raw('shakespeare-hamlet.txt')
with open('data.txt','w') as file:
    file.write(data)

In [18]:
from tensorflow.keras.preprocessing.text import Tokenizer
from tensorflow.keras.preprocessing.sequence import pad_sequences
from sklearn.model_selection import train_test_split

In [20]:

with open('data.txt','r') as file:
    text=file.read().lower()

In [25]:
tokenizer=Tokenizer()

In [27]:
tokenizer.fit_on_texts([text])

In [29]:
total_words=len(tokenizer.word_index)+1

In [31]:
total_words

4818

In [37]:
tokenizer.word_index

{'the': 1,
 'and': 2,
 'to': 3,
 'of': 4,
 'i': 5,
 'you': 6,
 'a': 7,
 'my': 8,
 'it': 9,
 'in': 10,
 'that': 11,
 'ham': 12,
 'is': 13,
 'not': 14,
 'his': 15,
 'this': 16,
 'with': 17,
 'your': 18,
 'but': 19,
 'for': 20,
 'me': 21,
 'lord': 22,
 'as': 23,
 'what': 24,
 'he': 25,
 'be': 26,
 'so': 27,
 'him': 28,
 'haue': 29,
 'king': 30,
 'will': 31,
 'no': 32,
 'our': 33,
 'we': 34,
 'on': 35,
 'are': 36,
 'if': 37,
 'all': 38,
 'then': 39,
 'shall': 40,
 'by': 41,
 'thou': 42,
 'come': 43,
 'or': 44,
 'hamlet': 45,
 'good': 46,
 'do': 47,
 'hor': 48,
 'her': 49,
 'let': 50,
 'now': 51,
 'thy': 52,
 'how': 53,
 'more': 54,
 'they': 55,
 'from': 56,
 'enter': 57,
 'at': 58,
 'was': 59,
 'oh': 60,
 'like': 61,
 'most': 62,
 'there': 63,
 'well': 64,
 'know': 65,
 'selfe': 66,
 'would': 67,
 'them': 68,
 'loue': 69,
 'may': 70,
 "'tis": 71,
 'vs': 72,
 'sir': 73,
 'qu': 74,
 'which': 75,
 'did': 76,
 'why': 77,
 'laer': 78,
 'giue': 79,
 'thee': 80,
 'ile': 81,
 'must': 82,
 'hath': 

In [47]:
input_sequences=[]
for line in text.split('\n'):
    token_list=tokenizer.texts_to_sequences([line])[0]
    for i in range(1,len(token_list)):
        sequence=token_list[:i+1]
        #print(sequence)
        input_sequences.append(sequence)

[1, 687]
[1, 687, 4]
[1, 687, 4, 45]
[1, 687, 4, 45, 41]
[1, 687, 4, 45, 41, 1886]
[1, 687, 4, 45, 41, 1886, 1887]
[1, 687, 4, 45, 41, 1886, 1887, 1888]
[1180, 1889]
[1180, 1889, 1890]
[1180, 1889, 1890, 1891]
[57, 407]
[57, 407, 2]
[57, 407, 2, 1181]
[57, 407, 2, 1181, 177]
[57, 407, 2, 1181, 177, 1892]
[407, 1182]
[407, 1182, 63]
[408, 162]
[408, 162, 377]
[408, 162, 377, 21]
[408, 162, 377, 21, 247]
[408, 162, 377, 21, 247, 882]
[18, 66]
[451, 224]
[451, 224, 248]
[451, 224, 248, 1]
[451, 224, 248, 1, 30]
[408, 407]
[451, 25]
[408, 6]
[408, 6, 43]
[408, 6, 43, 62]
[408, 6, 43, 62, 1893]
[408, 6, 43, 62, 1893, 96]
[408, 6, 43, 62, 1893, 96, 18]
[408, 6, 43, 62, 1893, 96, 18, 566]
[451, 71]
[451, 71, 51]
[451, 71, 51, 1894]
[451, 71, 51, 1894, 567]
[451, 71, 51, 1894, 567, 378]
[451, 71, 51, 1894, 567, 378, 80]
[451, 71, 51, 1894, 567, 378, 80, 3]
[451, 71, 51, 1894, 567, 378, 80, 3, 273]
[451, 71, 51, 1894, 567, 378, 80, 3, 273, 1181]
[408, 20]
[408, 20, 16]
[408, 20, 16, 1895]
[408,

In [49]:
max_sequence_len=max([len(line) for line in input_sequences])

In [51]:
max_sequence_len
#bir cümlenin max uzunluğu 


14

In [53]:
#pad_sequence işlemini bu sayıya göre yapıcaz

In [59]:
input_sequences=np.array(pad_sequences(input_sequences,maxlen=max_sequence_len,padding='pre'))

In [61]:
input_sequences

array([[   0,    0,    0, ...,    0,    1,  687],
       [   0,    0,    0, ...,    1,  687,    4],
       [   0,    0,    0, ...,  687,    4,   45],
       ...,
       [   0,    0,    0, ...,    4,   45, 1047],
       [   0,    0,    0, ...,   45, 1047,    4],
       [   0,    0,    0, ..., 1047,    4,  193]])

In [63]:
import tensorflow as tf

In [69]:
y=input_sequences[:,-1]
x=input_sequences[:,:-1]

In [67]:
y

array([ 687,    4,   45, ..., 1047,    4,  193])

In [171]:
y=tf.keras.utils.to_categorical(y,num_classes=total_words)
print(y)

[[0. 0. 0. ... 0. 0. 0.]
 [0. 0. 0. ... 0. 0. 0.]
 [0. 0. 0. ... 0. 0. 0.]
 ...
 [0. 0. 0. ... 0. 0. 0.]
 [0. 0. 0. ... 0. 0. 0.]
 [0. 0. 0. ... 0. 0. 0.]]


In [78]:
X_train,X_test,y_train,y_test=train_test_split(x,y,test_size=0.2)

In [86]:
from tensorflow.keras.models import Sequential
from tensorflow.keras.layers import Embedding,LSTM,Dense,Dropout
print(help(LSTM))

Help on class LSTM in module keras.src.layers.rnn.lstm:

class LSTM(keras.src.layers.rnn.dropout_rnn_cell_mixin.DropoutRNNCellMixin, keras.src.layers.rnn.base_rnn.RNN, keras.src.engine.base_layer.BaseRandomLayer)
 |  LSTM(units, activation='tanh', recurrent_activation='sigmoid', use_bias=True, kernel_initializer='glorot_uniform', recurrent_initializer='orthogonal', bias_initializer='zeros', unit_forget_bias=True, kernel_regularizer=None, recurrent_regularizer=None, bias_regularizer=None, activity_regularizer=None, kernel_constraint=None, recurrent_constraint=None, bias_constraint=None, dropout=0.0, recurrent_dropout=0.0, return_sequences=False, return_state=False, go_backwards=False, stateful=False, time_major=False, unroll=False, **kwargs)
 |  
 |  Long Short-Term Memory layer - Hochreiter 1997.
 |  
 |  See [the Keras RNN API guide](https://www.tensorflow.org/guide/keras/rnn)
 |  for details about the usage of RNN API.
 |  
 |  Based on available runtime hardware and constraints, thi

In [96]:
model=Sequential()
model.add(Embedding(total_words,100,input_length=max_sequence_len-1))
model.add(LSTM(150,use_bias=True,return_sequences=True))
model.add(Dropout(0.2))
model.add(LSTM(100))
model.add(Dense(total_words,activation='softmax'))
model.compile(optimizer='adam',loss='categorical_crossentropy',metrics=['accuracy'])

In [98]:
model.summary()

Model: "sequential_2"
_________________________________________________________________
 Layer (type)                Output Shape              Param #   
 embedding_2 (Embedding)     (None, 13, 100)           481800    
                                                                 
 lstm_3 (LSTM)               (None, 13, 150)           150600    
                                                                 
 dropout_1 (Dropout)         (None, 13, 150)           0         
                                                                 
 lstm_4 (LSTM)               (None, 100)               100400    
                                                                 
 dense_1 (Dense)             (None, 4818)              486618    
                                                                 
Total params: 1219418 (4.65 MB)
Trainable params: 1219418 (4.65 MB)
Non-trainable params: 0 (0.00 Byte)
_________________________________________________________________


In [100]:
model.fit(X_train,y_train,epochs=50,validation_data=(X_test,y_test),verbose=1)

Epoch 1/50


644/644 [==============================] - 17s 21ms/step - loss: 6.9065 - accuracy: 0.0330 - val_loss: 6.7337 - val_accuracy: 0.0359
Epoch 2/50
644/644 [==============================] - 12s 18ms/step - loss: 6.4656 - accuracy: 0.0366 - val_loss: 6.8314 - val_accuracy: 0.0445
Epoch 3/50
644/644 [==============================] - 11s 17ms/step - loss: 6.3296 - accuracy: 0.0438 - val_loss: 6.8939 - val_accuracy: 0.0503
Epoch 4/50
644/644 [==============================] - 11s 17ms/step - loss: 6.1922 - accuracy: 0.0506 - val_loss: 6.9375 - val_accuracy: 0.0497
Epoch 5/50
644/644 [==============================] - 11s 17ms/step - loss: 6.0560 - accuracy: 0.0544 - val_loss: 6.9789 - val_accuracy: 0.0538
Epoch 6/50
644/644 [==============================] - 11s 17ms/step - loss: 5.9188 - accuracy: 0.0640 - val_loss: 7.0311 - val_accuracy: 0.0589
Epoch 7/50
644/644 [==============================] - 11s 18ms/step - loss: 5.7819 - accuracy: 0.0719 - val_loss: 7.0777 - val_accurac

In [161]:
def predict_word(model,tokenizer,text,max_sequence_len):
    token_list=tokenizer.texts_to_sequences([text])[0]
    if(len(token_list)>=max_sequence_len):
        print('Cümle en fazla 13 kelime olabilir')
        return None
    token_list=pad_sequences([token_list],maxlen=max_sequence_len-1,padding='pre')
    predicted=model.predict(token_list,verbose=0)
    predicted_word_index=np.argmax(predicted,axis=1)
    for word,index in tokenizer.word_index.items():
        if(index==predicted_word_index):
            return word
    print("Error occured")
    return None
sentence='let me '
word=predict_word(model,tokenizer,sentence,max_sequence_len)
print("Cümle:",sentence)
if(word!=None):
    print("Tahmin:",word)

Cümle: let me 
Tahmin: bastard


In [165]:
model.save('lstm.keras')